/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "stateMachineLambda-express": {
      "name": string
      "type": "sst.aws.Function"
    }
    "stateMachineLambda-standard": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
